### ISSUE TITLE
Can't start with WEBSITE_DEVELOP=False flag

### ISSUE THREAD

**Issue by pashkash** [TellinaTool/tellina#10]
Hi.

To reproduce:
```
git clone https://github.com/TellinaTool/tellina.git tellina_test
cd tellina_test
python3 -m venv --system-site-packages ./venv
source ./venv/bin/activate
pip3 install tensorflow==1.15
pip3 install -r requirements.txt
git submodule update --init --remote
git submodule foreach git pull origin master
make submodule
make db
```

change `WEBSITE_DEVELOP=False` flag here https://github.com/TellinaTool/tellina/blob/master/website/views.py because I want to translate Natural commands into bash  

update `https://github.com/TellinaTool/tellina/blob/master/website/backend_interface.py` with:
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

```
# initialize FLAGS by parsing a dummy argument list
tf.compat.v1.flags.FLAGS(sys.argv[:1])
FLAGS = tf.compat.v1.flags.FLAGS
```

and 
```
# Create tensorflow session
sess = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(allow_soft_placement=True,
    log_device_placement=FLAGS.log_device_placement))

```

All changes here: https://github.com/TellinaTool/tellina/compare/master...pashkash:patch-1 

then run it
```
make run
```

and expect for the service, but get:
```
ValueError: Provided a prefix or suffix of None: ? and 200
```

**Comment by todpole3** [comment]
@pashkash Many thanks for raising this issue.

I have pushed a fix in the code.

In addition, the problem was caused by the [ML submodule](https://github.com/TellinaTool/nl2bash) being changed to Tensorflow2.0. Therefore you need to change this step `pip3 install tensorflow==1.15` to `pip3 install tensorflow==2.0`.

Let me know if this solves the problem. If so you may also close this issue.

**Comment by pashkash** [comment]
I still can't use the web-service, it doesn't show me suggestions by HTTP requests, but because of your fixes, now I am able to have a copy of `backend_interface.py` with this appendix
```
if __name__ == "__main__":
  sentence = 'Find all pdf files'
  
  batch_outputs, output_logits = decode_tools.translate_fun(
      sentence, sess, model, vocabs, FLAGS, slot_filling_classifier)
  
  print("batch_outputs",batch_outputs) 
  print("the first one suggestion",str(batch_outputs[0][0])) 
  print("the first one suggestion bash command",str(batch_outputs[0][0][1])) 
```
to run it inside `tellina_learning_module` folder and satisfy my curiosity. Many thanks to you! No disturbing from my side anymore. 
Amazing.
